name: Angular Build

on:
  push:
     tags: 
     - 'patch-*'
     - 'minor-*'
     - 'major-*'
    
jobs:
  check-branch-tag:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo $raw)"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."
  build:
    runs-on: ubuntu-latest
    needs: check-branch-tag
    if: needs.check-branch-tag.outputs.branch == 'origin/main'
    steps:
    - uses: actions/checkout@v4
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.19.0
    - name: Install Dependencies
      run: npm install
    - name: Get Next Version
      id: version
      run: | 
        {
          echo "Version=$(curl -k -L -X GET 'https://openhomeproject.com/system/Version/GetNextVersion?versionIncrement=${{github.ref_name}}' -H 'x-api-key: ${{ secrets.APIKEY }}')"  
        } >> $GITHUB_OUTPUT
    - name: 👷 Build & Publish
      run: npm run build --production
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Zip artifact for push
      run: |
        { 
        mkdir ./zip 
        cd dist/ambient-zero-site/browser
        zip  -r '../../../zip/${{ steps.date.outputs.date }}_${{steps.version.outputs.Version}}.zip' ./*
        }
    - name: 📂 Upload File  
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.FTP_SERVER }}                  
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        compress: true                             
        forceUpload: true                          
        localDir: './zip'                              
        remoteDir: ${{ secrets.FTP_FILE_PATH }}   
    - name: Deploy
      run: | 
        curl -k -L -X POST 'https://openhomeproject.com/system/Deploy/DeployApp' -H 'x-api-key: ${{ secrets.APIKEY }}' -H 'Content-Type: application/json' --data-raw '{"fileName": "${{ steps.date.outputs.date }}_${{github.ref_name}}.zip", "version": "${{ steps.version.outputs.Version }}"}'
       
