# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Angular Build

on:
  push:
     tags: 
     - 'v*.*.*'
    
jobs:
  check-branch-tag:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo $raw)"
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branches where this tag exists : $branch."
  build:

    runs-on: ubuntu-latest
    needs: check-branch-tag
    if: needs.check-branch-tag.outputs.branch == 'origin/main'
    steps:
    - uses: actions/checkout@v4
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.19.0
    - name: Install Dependencies
      run: npm install
    - name: 👷 Build & Publish
      run: npm run build --production
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Zip artifact for push
      run: mkdir ./zip && zip -r "./zip/release_${{ steps.date.outputs.date }}_${{ github.ref_name }}.zip" ./release
    - name: 📂 Upload File  
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.FTP_SERVER }}                  
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        compress: true                             
        forceUpload: true                          
        localDir: './zip'                              
        remoteDir: '/releases/AmbientZero/Web'     
